// HANDLERS 
export const FORM = 'FORM'
export const FORM_CLOSE = 'FORM_CLOSE'

// UPLOAD
export const UPLOADING = 'UPLOADING'
export const UPLOADING_SUCCESS = 'UPLOADING_SUCCESS'
export const UPLOADING_FAIL = 'UPLOADING_FAIL'
export const REMOVE_FILE_SUCCESS = 'REMOVE_FILE_SUCCESS'
export const REMOVE_FILE_FAIL = 'REMOVE_FILE_FAIL'