// ITEM

export const GET_ITEMS = 'GET_ITEMS'
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS'
export const GET_ITEMS_FAIL = 'GET_ITEMS_FAIL'

export const GET_BREADCRUMBS = 'GET_BREADCRUMBS'
export const GET_BREADCRUMBS_SUCCESS = 'GET_BREADCRUMBS_SUCCESS'
export const GET_BREADCRUMBS_FAIL = 'GET_BREADCRUMBS_FAIL'

export const ADD_ITEM = 'ADD_ITEM'
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS'
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL'

export const UPDATE_ITEM = 'UPDATE_ITEM'
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS'
export const UPDATE_ITEM_FAIL = 'UPDATE_ITEM_FAIL'

export const REMOVE_ITEM = 'REMOVE_ITEM'
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS'
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL'

export const SELECT_ITEM = 'SELECT_ITEM'
export const UNSELECT_ITEMS = 'UNSELECT_ITEMS'

export const MOVE_ITEMS = 'MOVE_ITEMS'
export const MOVE_ITEMS_SUCCESS = 'MOVE_ITEMS_SUCCESS'
export const MOVE_ITEMS_FAIL = 'MOVE_ITEMS_FAIL'

