// PROFILE
export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'

export const ADD_PROFILE = 'ADD_PROFILE'
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS'
export const ADD_PROFILE_FAIL = 'ADD_PROFILE_FAIL'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export const REMOVE_PROFILE = 'REMOVE_PROFILE'
export const REMOVE_PROFILE_SUCCESS = 'REMOVE_PROFILE_SUCCESS'
export const REMOVE_PROFILE_FAIL = 'REMOVE_PROFILE_FAIL'

export const RESOTRE_PROFILE_SUCCESS = 'RESOTRE_PROFILE_SUCCESS'
export const RESOTRE_PROFILE_FAIL = 'RESOTRE_PROFILE_FAIL'

