// AUTH

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

// USER
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

// MODAL
export const MODAL = 'MODAL';
export const DROPDOWN = 'DROPDOWN';

// ALERTS

export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

export const SET_NOTE =  'SET_NOTE'
export const MOVE_NOTE =  'MOVE_NOTE'
export const REMOVE_NOTE = 'REMOVE_NOTE'
  
// REST

export const IN_PROGRESS = 'IN_PROGRESS';


// SEARCH 
export const GET_QUERY_SUCCESS = 'GET_QUERY_SUCCESS';
export const GET_QUERY_LOADING = 'GET_QUERY_LOADING';
export const GET_QUERY_FAIL = 'GET_QUERY_FAIL';

// PROFILE
export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'

export const ADD_PROFILE = 'ADD_PROFILE'
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS'
export const ADD_PROFILE_FAIL = 'ADD_PROFILE_FAIL'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export const REMOVE_PROFILE = 'REMOVE_PROFILE'
export const REMOVE_PROFILE_SUCCESS = 'REMOVE_PROFILE_SUCCESS'
export const REMOVE_PROFILE_FAIL = 'REMOVE_PROFILE_FAIL'

export const RESOTRE_PROFILE_SUCCESS = 'RESOTRE_PROFILE_SUCCESS'
export const RESOTRE_PROFILE_FAIL = 'RESOTRE_PROFILE_FAIL'

// ITEM

export const GET_ITEMS = 'GET_ITEMS'
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS'
export const GET_ITEMS_FAIL = 'GET_ITEMS_FAIL'

export const GET_BREADCRUMBS = 'GET_BREADCRUMBS'
export const GET_BREADCRUMBS_SUCCESS = 'GET_BREADCRUMBS_SUCCESS'
export const GET_BREADCRUMBS_FAIL = 'GET_BREADCRUMBS_FAIL'

export const ADD_ITEM = 'ADD_ITEM'
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS'
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL'

export const UPDATE_ITEM = 'UPDATE_ITEM'
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS'
export const UPDATE_ITEM_FAIL = 'UPDATE_ITEM_FAIL'

export const REMOVE_ITEM = 'REMOVE_ITEM'
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS'
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL'

export const SELECT_ITEM = 'SELECT_ITEM'
export const UNSELECT_ITEMS = 'UNSELECT_ITEMS'

export const MOVE_ITEMS = 'MOVE_ITEMS'
export const MOVE_ITEMS_SUCCESS = 'MOVE_ITEMS_SUCCESS'
export const MOVE_ITEMS_FAIL = 'MOVE_ITEMS_FAIL'

// UPLOAD
export const UPLOADING = 'UPLOADING'
export const UPLOADING_SUCCESS = 'UPLOADING_SUCCESS'
export const UPLOADING_FAIL = 'UPLOADING_FAIL'
export const REMOVE_FILE_SUCCESS = 'REMOVE_FILE_SUCCESS'
export const REMOVE_FILE_FAIL = 'REMOVE_FILE_FAIL'
// UTILS

export const CLEAN_UP = 'CLEAN_UP'

// FORM 
export const FORM = 'FORM'
export const FORM_CLOSE = 'FORM_CLOSE'
