// AUTH

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

// USER
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

// MODAL
export const MODAL = 'MODAL';
export const DROPDOWN = 'DROPDOWN';
export const EDIT = 'EDIT';

// ALERTS

export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

// REST

export const IN_PROGRESS = 'IN_PROGRESS';


// SEARCH 
export const GET_QUERY_SUCCESS = 'GET_QUERY_SUCCESS';
export const GET_QUERY_LOADING = 'GET_QUERY_LOADING';
export const GET_QUERY_FAIL = 'GET_QUERY_FAIL';

// PROFILE
export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'

// ITEM

export const GET_ITEMS = 'GET_ITEM'
export const GET_ITEMS_SUCCESS = 'GET_ITEM_SUCCESS'
export const GET_ITEMS_FAIL = 'GET_ITEM_FAIL'

export const ADD_ITEM = 'ADD_ITEM'
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS'
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL'

export const UPDATE_ITEM = 'UPDATE_ITEM'
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS'
export const UPDATE_ITEM_FAIL = 'UPDATE_ITEM_FAIL'

export const REMOVE_ITEM = 'REMOVE_ITEM'
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS'
export const REMOVE_ITEM_FAIL = 'REMOVE_ITEM_FAIL'


